### ISSUE TITLE
[TASK][Agent-Host]to dequeue from SQS and start to crawling app

### ISSUE THREAD

**Issue by koshilife** [koshilife/android-autosnap#19]
## Process Controller Specification
We check if connected android devices are able to start uiautomator test.
If more than one device is available then start to test and create a lock file, else finish program.
We will remove the lock file after finish the test.

## Tasks

- [x] #20 get adb devices information
- [x] create/remove lock file
- [x] run uiautomator test

**Comment by koshilife** [comment]
we referred to the following.
https://stackoverflow.com/questions/636561/how-can-i-run-an-external-command-asynchronously-from-python
